language: python
python:
  - "3.7"

install:
  - "python setup.py install"
  - "pip install nose==1.3.7 coverage==4.3.4 coveralls"
  - "pip install pydocstyle pycodestyle black isort"
  - "pip list"

script:
  - nosetests
  - pycodestyle ebus
  - pydocstyle ebus
  - black . --check
  - isort

after_success:
  coveralls
